INSERT INTO core_student (name, rank) values ('Acauã Emanuel Ribeiro','B');
INSERT INTO core_student (name, rank) values ('Adrian Grosch','A');
INSERT INTO core_student (name, rank) values ('Adrian Schlei','B');
INSERT INTO core_student (name, rank) values ('Adriano Henrique dos Santos','B');
INSERT INTO core_student (name, rank) values ('Alan Marcos Kubiak','B');
INSERT INTO core_student (name, rank) values ('Bianca Santana Hillesheim','A');
INSERT INTO core_student (name, rank) values ('Carla Tahís Dalmolin','B');
INSERT INTO core_student (name, rank) values ('Cesar Augusto Freire','B');
INSERT INTO core_student (name, rank) values ('Eduardo Radloff','A');
INSERT INTO core_student (name, rank) values ('Elias Celso Mendes','A');
INSERT INTO core_student (name, rank) values ('Eloisa Renata Schons','B');
INSERT INTO core_student (name, rank) values ('Ericson Franzen','A');
INSERT INTO core_student (name, rank) values ('Gustavo Ceola','B');
INSERT INTO core_student (name, rank) values ('Haroldo Luiz Beyer Bacellar','B');
INSERT INTO core_student (name, rank) values ('Igor Ceola','B');
INSERT INTO core_student (name, rank) values ('Igor Hafemann','B');
INSERT INTO core_student (name, rank) values ('Igor José Xavier','A');
INSERT INTO core_student (name, rank) values ('Jackson Castilho da Luz','B');
INSERT INTO core_student (name, rank) values ('Jackson Correa Gutz','B');
INSERT INTO core_student (name, rank) values ('Jean Carlos Tessarollo','B');
INSERT INTO core_student (name, rank) values ('João Elias Engelbrecht Kayser','A');
INSERT INTO core_student (name, rank) values ('João Victor Cardoso de Souza','B');
INSERT INTO core_student (name, rank) values ('Jonas Figueredo','B');
INSERT INTO core_student (name, rank) values ('José Carvalho Matos Júnior','B');
INSERT INTO core_student (name, rank) values ('Juarez da Cunha','B');
INSERT INTO core_student (name, rank) values ('Karolayne Silveira Mendes','A');
INSERT INTO core_student (name, rank) values ('Leandro Luiz Schoninger Filho','B');
INSERT INTO core_student (name, rank) values ('Lucas Lombardi Floriano','B');
INSERT INTO core_student (name, rank) values ('Lucas Samuél Karsten','A');
INSERT INTO core_student (name, rank) values ('Maicon Amarante Mendes','B');
INSERT INTO core_student (name, rank) values ('Marcelo Fellipe Hammes','A');
INSERT INTO core_student (name, rank) values ('Márcio Schroeder da Costa','B');
INSERT INTO core_student (name, rank) values ('Matheus Henrique Costa','B');
INSERT INTO core_student (name, rank) values ('Matheus Henrique Setoyama da Maia','B');
INSERT INTO core_student (name, rank) values ('Matheus Parro de Sousa','A');
INSERT INTO core_student (name, rank) values ('Mauricio Manoel Sagaz','A');
INSERT INTO core_student (name, rank) values ('Maurício Sucheuski','A');
INSERT INTO core_student (name, rank) values ('Rafael Oliveira Silva','B');
INSERT INTO core_student (name, rank) values ('Rafael Vinícius Schneider','A');
INSERT INTO core_student (name, rank) values ('Rafael Zink','A');
INSERT INTO core_student (name, rank) values ('Raimundo Nonato da Silva Nascimento','A');
INSERT INTO core_student (name, rank) values ('Renan Ricardo Holler','B');
INSERT INTO core_student (name, rank) values ('Rodrigo Cassiano','A');
INSERT INTO core_student (name, rank) values ('Roger Henrique Cavichioli','B');
INSERT INTO core_student (name, rank) values ('Rudney Dolla','A');
INSERT INTO core_student (name, rank) values ('Ryan Carlos Meneghelli','B');
INSERT INTO core_student (name, rank) values ('Thiago Samuel Stahnke','A');